<?php

declare(strict_types=1);

namespace GameOfLife\Commands;

use GameOfLife\Game;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class PlayCommand extends Command
{
    protected static $defaultName = 'game:play';

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $file = $input->getArgument('file');
        //$game = new Game()
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}